name: C++ CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y g++

      - name: Build
        run: g++ -o output yung.cpp

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: ./output
