name: C++ CI

on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        run: cl /EHsc /Fe:output.exe yung.cpp

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: ./output.exe
